project:
  type: website
  output-dir: _site

website:
  title: "TidyTuesday 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/thedbcooper/tidytuesday-2026
  repo-url: https://github.com/thedbcooper/tidytuesday-2026
  repo-actions: [issue, source]

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: show
    code-tools: true

execute:
  freeze: auto
