project:
  type: website
  output-dir: _site

website:
  open-graph: true
  title: "TidyTuesday 2026"
  navbar:
    background: "#2c3419"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: github
        href: https://github.com/thedbcooper/tidytuesday-2026
  repo-url: https://github.com/thedbcooper/tidytuesday-2026
  repo-actions: [issue, source]

format:
  html:
    theme: [default, styles.scss]
    toc: true
    toc-location: left
    code-fold: show
    code-tools: true

execute:
  freeze: true